apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp-chart.fullname" . }}
  labels:
    {{- include "myapp-chart.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8081'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "myapp-chart.selectorLabels" . | nindent 4 }}
